# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'
services:

  ##----Start: EII Base Images -- This Base images must be included for building any EII servcies ----
  ## Define ia_eiibase service
  ia_configmgr_agent:
    read_only: false
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_configmgr_agent:${EII_VERSION}
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    restart: unless-stopped
    container_name: ia_configmgr_agent
    environment:
      SERVICES: "EtcdUI,Telegraf,InfluxDBConnector,Kapacitor,Grafana,OpcuaExport,RestDataExport,mqtt-broker,mqtt-publisher"
      AppName: "ConfigMgrAgent"
      HOST_IP: $HOST_IP
      HOST_TIME_ZONE: $HOST_TIME_ZONE
      EII_INSTALL_PATH: $EII_INSTALL_PATH
      SOCKET_DIR: $SOCKET_DIR
      TC_DISPATCHER_PATH: $TC_DISPATCHER_PATH
      DEV_MODE: $DEV_MODE
      ETCDCTL_API: 3
      ETCD_HOST: $ETCD_HOST
      ETCD_DATA_DIR: $ETCD_DATA_DIR
      ETCD_CLIENT_PORT: $ETCD_CLIENT_PORT
      ETCD_PEER_PORT: $ETCD_PEER_PORT
      ETCD_NAME: $ETCD_NAME
      ETCDROOT_PASSWORD: $ETCDROOT_PASSWORD
      ETCD_PREFIX: $ETCD_PREFIX
      no_proxy: $eii_no_proxy,0.0.0.0:$ETCD_CLIENT_PORT,0.0.0.0:$ETCD_PEER_PORT
      NO_PROXY: $eii_no_proxy,0.0.0.0:$ETCD_CLIENT_PORT,0.0.0.0:$ETCD_PEER_PORT
    networks:
    - eii
    ports:
    - $ETCD_CLIENT_PORT:$ETCD_CLIENT_PORT
    - $ETCD_PEER_PORT:$ETCD_PEER_PORT
    ipc: "none"
    volumes:
    - ./Certificates:/EII/Certificates:rw
    - ./eii_config.json:/EII/etcd/config/eii_config.json
    - $EII_INSTALL_PATH/data/:$ETCD_DATA_DIR/etcd_capture
    - $EII_INSTALL_PATH:$EII_INSTALL_PATH
    - $EII_INSTALL_PATH/models/:/app/models/
    - $EII_INSTALL_PATH/sockets:$SOCKET_DIR
    - $EII_INSTALL_PATH/data:/data
    - $EII_INSTALL_PATH/tools_output:/tools_output
    - $EII_INSTALL_PATH/saved_images:/saved_images
    - $EII_INSTALL_PATH/rde:/rde
    - $TC_DISPATCHER_PATH:$TC_DISPATCHER_PATH
  ia_etcd_ui:
    read_only: false
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_etcd_ui:${EII_VERSION}
    container_name: ia_etcd_ui
    hostname: ia_etcd_ui
    restart: unless-stopped
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    environment:
      AppName: "EtcdUI"
      DEV_MODE: ${DEV_MODE}
      NGINX_PORT: 7071
      no_proxy: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      ETCD_ENDPOINT: "$ETCD_HOST:$ETCD_CLIENT_PORT"
    networks:
    - eii
    volumes:
    - "vol_etcd_keeper:/opt/nginx"
    - ./Certificates/EtcdUI:/run/secrets/EtcdUI:ro
    - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
    ipc: "none"
    ports:
    - 7071:7071
    - 7070:7070

  ia_telegraf:
    container_name: ia_telegraf
    hostname: ia_telegraf
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_telegraf:${EII_VERSION}
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    read_only: true
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    environment:
      AppName: "Telegraf"
      DEV_MODE: ${DEV_MODE}
      no_proxy: "${ETCD_HOST},ia_influxdbconnector"
      NO_PROXY: "${ETCD_HOST},ia_influxdbconnector"
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      MQTT_BROKER_HOST: ${HOST_IP}
      INFLUX_SERVER: ${HOST_IP}
      INFLUXDB_PORT: $INFLUXDB_PORT
      ETCD_PREFIX: ${ETCD_PREFIX}
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
    ports:
    - 65077:65077
    networks:
    - eii
    volumes:
    - "vol_temp_telegraf:/tmp/"
    - "vol_eii_socket:${SOCKET_DIR}"
    - ./Certificates/Telegraf:/run/secrets/Telegraf:ro
    - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro

  ia_influxdbconnector:
    read_only: true
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_influxdbconnector:${EII_VERSION}
    container_name: ia_influxdbconnector
    hostname: ia_influxdbconnector
    restart: unless-stopped
    environment:
      AppName: "InfluxDBConnector"
      DEV_MODE: ${DEV_MODE}
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: ${ETCD_HOST}
      NO_PROXY: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      INFLUXDB_TLS_CIPHERS: ${TLS_CIPHERS}
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
    volumes:
    - "vol_influxdb_data:/influxdata"
    - "${EII_INSTALL_PATH}/sockets:${SOCKET_DIR}"
    - ./Certificates/InfluxDBConnector:/run/secrets/InfluxDBConnector:ro
    - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
    - "vol_influxdb_conf:/tmp/influxdb"
    ports:
    - "$INFLUXDB_PORT:$INFLUXDB_PORT"
    - 65145:65145
    - 65030:65030
    - 65031:65031
    - 65032:65032
    - 65033:65033
    - 65034:65034
    networks:
    - eii

  ia_kapacitor:
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_kapacitor:${EII_VERSION}
    container_name: ia_kapacitor
    hostname: ia_kapacitor
    read_only: true
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    environment:
      AppName: "Kapacitor"
      DEV_MODE: ${DEV_MODE}
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: "${ETCD_HOST},ia_influxdbconnector,ia_kapacitor"
      NO_PROXY: "${ETCD_HOST},ia_influxdbconnector,ia_kapacitor"
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      KAPACITOR_URL: http://ia_kapacitor:$KAPACITOR_PORT/
      KAPACITOR_UNSAFE_SSL: "true"
      KAPACITOR_INFLUXDB_0_URLS_0: http://ia_influxdbconnector:$INFLUXDB_PORT/
      INFLUX_SERVER: 'ia_influxdbconnector'
      KAPACITOR_SERVER: 'ia_kapacitor'
      KAPACITOR_PORT: $KAPACITOR_PORT
      ETCD_PREFIX: ${ETCD_PREFIX}
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
    networks:
    - eii
    volumes:
    - "vol_temp_kapacitor:/tmp/"
    - "vol_eii_socket:${SOCKET_DIR}"
    - "vol_dev_shm:/dev/shm"
    - ./Certificates/Kapacitor:/run/secrets/Kapacitor:ro
    - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
    ports:
    - "$KAPACITOR_PORT:$KAPACITOR_PORT"

  ia_grafana:
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_grafana:${EII_VERSION}
    container_name: ia_grafana
    hostname: ia_grafana
    read_only: false
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    environment:
      AppName: "Grafana"
      DEV_MODE: ${DEV_MODE}
      no_proxy: "${ETCD_HOST},ia_influxdbconnector"
      NO_PROXY: "${ETCD_HOST},ia_influxdbconnector"
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      HOST_IP: ${HOST_IP}
      INFLUX_SERVER: ${HOST_IP}
      GRAFANA_SERVER: '0.0.0.0'
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
    networks:
    - eii
    volumes:
    - "vol_temp_grafana:/tmp"
    - "vol_eii_socket:${SOCKET_DIR}"
    - ./Certificates/Grafana:/run/secrets/Grafana:ro
    - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
    ports:
    - "$GRAFANA_PORT:$GRAFANA_PORT"
    - 5003:5003
    - 5004:5004

  ia_opcua_export:
    read_only: true
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_opcua_export:${EII_VERSION}
    container_name: ia_opcua_export
    hostname: ia_opcua_export
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    environment:
      AppName: "OpcuaExport"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
    networks:
    - eii
    ports:
    - 65003:65003

    volumes:
    - "vol_eii_socket:${SOCKET_DIR}"
    - "vol_opcua:/tmp"
    - ./Certificates/OpcuaExport:/run/secrets/OpcuaExport:ro
    - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
    - ./Certificates/opcua:/run/secrets/opcua:ro

  ia_rest_export:
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_rest_export:${EII_VERSION}
    container_name: ia_rest_export
    hostname: ia_rest_export
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    read_only: true
    environment:
      AppName: "RestDataExport"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${ETCD_HOST}
      NO_PROXY: ${no_proxy}
      RequestEP: "ImageStore"
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      HTTP_METHOD_FETCH_METADATA: ${HTTP_METHOD_FETCH_METADATA}
    networks:
    - eii
    volumes:
    - "${EII_INSTALL_PATH}/sockets:${SOCKET_DIR}"
    - "${EII_INSTALL_PATH}:${EII_INSTALL_PATH}"
    - ./Certificates/RestDataExport:/run/secrets/RestDataExport:ro
    - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
    ports:
    - 8087:8087

  neuron:
    container_name: neuron
    hostname: neuron
    image: emqx/neuron:2.2.3
    networks:
    - eii
    ports:
    - 7000:7000
    - 7001:7001
    volumes:
    - nng-ipc:/tmp 

  ekuiper:
    container_name: ekuiper
    hostname: ekuiper
    image: lfedge/ekuiper:1.6.1-slim-python
    environment:
      MQTT_SOURCE_DEFAULT_SERVER: "tcp://cloud.host:1883"
      KUIPER_BASIC_CONSOLELOG: "true"
      KUIPER_BASIC_IGNORECASE: "false"
    networks:
    - eii
    ports:
    - 9081:9081
    - 127.0.0.1:20498:20498
    volumes:
    - nng-ipc:/tmp 

  ekuiper_manager:
    container_name: ekuiper_manager
    hostname: ekuiper_manager
    image: emqx/ekuiper-manager:1.6.1
    networks:
    - eii
    ports:
    - 9082:9082  
  
  emqx:
    container_name: emqx
    hostname: emqx
    image: emqx/emqx:4.4.4
    networks:
    - eii
    ports:
    - 1883:1883
    - 18083:18083
    - 8083:8083

networks:
  eii:
    driver: bridge
volumes:
  vol_eii_socket:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ${EII_INSTALL_PATH}/sockets
  vol_etcd_keeper:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  vol_temp_telegraf:
    driver: local
    driver_opts:
      type: tmpfs
      o: "size=5K"
      device: tmpfs
  vol_influxdb_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  vol_influxdb_conf:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  vol_temp_kapacitor:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  vol_dev_shm:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  vol_temp_grafana:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  vol_opcua:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  nng-ipc:
